= View. Веб-система для перегляду фильмів : Запити зацікавлених осіб
Гуськов Данило; Олійник Юлія; Поліщук Степан; Маїк Богдан
Версія 1.0, 21 вересня 2020 року
:toc: macro
:toc-title: Зміст
:sectnums:
:chapter-label:

<<<

[preface]
== Список змін
[cols=4*,options="header"]
|===
|Дата
|Версія
|Опис
|Автори

|21.09.2020
|1.0
|Створення документа
|Гуськов Данило; Олійник Юлія; Поліщук Степан; Маїк Богдан
|===

<<<

toc::[]

<<<

== Вступ
У цьому документі описуються засоби зацікавлених осіб для веб-системи для перегляду фильмів. Зацікавленими особами є майбутні користувачі системи та його команда адміністрації.

=== Мета
Метою документу є визначення основних вимог до функції, що виконує система, а також правил та обмежень, що стосуються системи.

=== Контекст
Перелік вимог, що описані у цьому документі, є основою технічного завдання на розробку веб-системи  для перегляду фільмів.

== Короткий огляд продукту
View буде являти собою веб-систему для перегляду фільмів. Користувачі системи зможуть переглядати, оцінювати, коментувати фільми, створювати рекомендаційні списки на основі переглянутих фільмів, а також поширювати посилання на фільм в соціальних мережах.

== Характеристика ділових процесів

=== Призначення системи
Веб-система View призначений для надання користувачам можливостей щодо перегляду фільмів завантажених адміністраторами, та модераторами сервісу.

=== Взаємодія з користувачами
Взаємодія з користувачами буде проходити за допомогою веб-системи.

=== Характеристика бізнес-процесу
Управління системою буде виконуватись за допомогою відокремленого розділу веб-системи та за допомогою спеціальної команди адміністрування в складі адміністраторів та модераторів системи.

== Функціональність.

=== Функція перегляду фільму.
Будь-який користувач системи (анонімні та зареєстровані користувачі, члени команди адміністрування) може переглянути викладені на сервісі фільми.

=== Функція оцінювання фільму.
Зареєстровані користувачі можуть оцінити переглянутий відеоролик. Сумарна оцінка відеоролику показується у його описі.

=== Функції пов'язані з каналами користувачів.
Зареєстровані користувачі можуть генерувати свій список рекомендованих фільмів на основі все переглянутих

=== Функція комментування фільма.
Зареєстрований користувач, може залишити коментар, коментарі будуть відображені під описом фільму.

=== Функція модерації.
Оператори, та адміністратори системи загружають нові відео матеріали та мають можливість за необхідністю видалити їх, за запитом автора.

== Доступність.
=== Локалізація.
Інтерфейс веб-системи повинен бути локалізованим на англійську, російську, українську мови.

=== Програмні платформи.
Веб-система повинен коректно показуватися в усіх веб-браузерах останніх версій.

=== Інтерфейс.
Інтерфейс веб-системи повинен бути адаптований для роботи людей з різними вадами здоров'я.

== Відмовостійкість.
Система повинна мати високий рівень відмовостійкості. Він буде забезпечуватися резервним копіюванням даних, дублюванням баз даних, серверів тощо.

== Захищеність.
Дані користувачів системи повинні буди надійно захищенні від сторонніх осіб шляхом шифрування та організації аутентифікованого доступу.
